---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

# image will be published to ghcr.io/<user>/<name>
name: aurora-nvidia-custom
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx-nvidia
image-version: stable-daily # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system      # copies files/system/ into your image's /.
        destination: /      # put configuration files you want in /etc/ on a booted system

  - type: rpm-ostree
    repos:
      - microsoft-edge.repo
    install:
      - git
      - git-lfs
      - git-credential-libsecret
      - opensc
      - firefox
      - nm-connection-editor
      - screen
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - libxml2 # Ansible requirement
      - libxslt # Ansible requirement
      - python3.12
      - microsoft-edge-stable
    optfix:
      - microsoft

  - type: bling
    install:
      - 1password

  - type: default-flatpaks
    configurations:
    - scope: user
      repo:
        # you can override the title to make inclusion of both system and user repos clearer
        title: Flathub (user)
    - notify: true
      scope: system
      repo:
        title: Flathub (system)
      install: # system flatpaks we want all users to have and not remove    install:
        - org.kde.okular
        - org.kde.kile
        - org.kde.kdenlive
        - org.kde.isoimagewriter
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      # remove:
      # # - org.gnome.eog

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans

  - type: systemd
    user:
      enabled:
        - podman.socket

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
