---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

# image will be published to ghcr.io/<user>/<name>
name: aurora-nvidia-custom
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx-nvidia-open
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      files:
        add:
          - microsoft-edge.repo
          - 1password.repo
        remove:
          - negativo17-fedora-multimedia
          - rpmfusion-free
          - rpmfusion-free-updates
          - rpmfusion-nonfree
          - rpmfusion-nonfree-updates
    install:
      packages:
        - libxml2-devel
        - libxslt-devel
        - python3-devel
        - 1password
        - 1password-cli
        - ccid
        - firefox
        - git
        - git-credential-libsecret
        - git-lfs
        - microsoft-edge-stable
        - nss-tools
        - nm-connection-editor
        - nodejs
        - npm
        - opensc
        - pcsc-lite
        - pcsc-tools
        - python3.12
        - screen
        - sshpass
        - uv
        - zsh-autosuggestions
        - zsh-syntax-highlighting

  - type: default-flatpaks
    configurations:
    - scope: user
      repo:
        title: Flathub (user)
    - notify: true
      scope: system
      repo:
        title: Flathub (system)
      install:
        - org.kde.okular
        - org.kde.kile
        - org.kde.kdenlive
        - org.kde.isoimagewriter
        - org.openrgb.OpenRGB

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans

  - type: systemd
    user:
      enabled:
        - podman.socket

  - type: signing
